import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docs: [
    'introduction',
    'visual-identity',
    {
      type: 'category',
      label: 'Foundation',
      collapsed: false,
      items: [
        'foundation/colors',
        'foundation/motion',
        'foundation/patterns',
        'foundation/shadows',
        'foundation/spacing',
        'foundation/textures',
        'foundation/typography',
      ],
    },
    {
      type: 'category',
      label: 'Components',
      collapsed: false,
      items: [
        {
          type: 'category',
          label: 'Atoms',
          collapsed: true,
          items: [
            'components/atoms/badge',
            'components/atoms/button',
            'components/atoms/die-chip',
            'components/atoms/grid',
            'components/atoms/icon',
            'components/atoms/row',
            'components/atoms/segmented-control',
            'components/atoms/selectable-tile',
            'components/atoms/separator',
            'components/atoms/stack',
            'components/atoms/status-callout',
            'components/atoms/text',
            'components/atoms/text-area',
            'components/atoms/text-field',
            'components/atoms/toggle',
          ],
        },
        {
          type: 'category',
          label: 'Molecules',
          collapsed: true,
          items: [
            'components/molecules/action-footer',
            'components/molecules/card',
            'components/molecules/card-matt',
            'components/molecules/character-card',
            'components/molecules/deck',
            'components/molecules/dice-result',
            'components/molecules/die-selector',
            'components/molecules/difficulty-badge',
            'components/molecules/doom-clock',
            'components/molecules/doom-clock-transition',
            'components/molecules/effort-band',
            'components/molecules/phase-header',
            'components/molecules/player-avatar',
            'components/molecules/playing-card',
            'components/molecules/result-banner',
            'components/molecules/strike-indicator',
            'components/molecules/tab-bar',
            'components/molecules/trophy-indicator',
            'components/molecules/waiting-indicator',
            'components/molecules/weakness-tracker',
          ],
        },
        {
          type: 'category',
          label: 'Organisms',
          collapsed: true,
          items: [
            'components/organisms/act-break-overlay',
            'components/organisms/character-bar',
            'components/organisms/chat-panel',
            'components/organisms/game-board',
            'components/organisms/header',
            'components/organisms/phase-display',
            'components/organisms/phase-panel',
            'components/organisms/player-panel',
            'components/organisms/scene-challenge-overlay',
            'components/organisms/transition-overlay',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Patterns',
      collapsed: false,
      items: [
        'patterns/anti-patterns',
        'patterns/decision-trees',
        'patterns/theme-contract',
      ],
    },
  ],
};

export default sidebars;
