import { render, screen, fireEvent } from '@testing-library/react';
import { describe, it, expect, vi } from 'vitest';
import { SceneChallengeOverlay } from './SceneChallengeOverlay';

const defaultProps = {
  visible: true,
  prompt: 'A heavy door slams shut behind you.',
  suitTheme: 'Power (Physical threat)',
  suitIcon: 'shield',
  difficulty: 5,
  imageSrc: '/textures/scenes/spades.png',
  onDismiss: vi.fn(),
  onExited: vi.fn(),
};

describe('SceneChallengeOverlay', () => {
  it('renders when visible', () => {
    render(<SceneChallengeOverlay {...defaultProps} />);
    expect(screen.getByRole('dialog')).toBeInTheDocument();
  });

  it('does not render when not visible', () => {
    render(<SceneChallengeOverlay {...defaultProps} visible={false} />);
    expect(screen.queryByRole('dialog')).not.toBeInTheDocument();
  });

  it('calls onDismiss when backdrop is clicked', () => {
    const onDismiss = vi.fn();
    render(<SceneChallengeOverlay {...defaultProps} onDismiss={onDismiss} />);
    fireEvent.click(screen.getByRole('dialog'));
    expect(onDismiss).toHaveBeenCalledTimes(1);
  });

  it('calls onDismiss on Enter key', () => {
    const onDismiss = vi.fn();
    render(<SceneChallengeOverlay {...defaultProps} onDismiss={onDismiss} />);
    fireEvent.keyDown(screen.getByRole('dialog'), { key: 'Enter' });
    expect(onDismiss).toHaveBeenCalledTimes(1);
  });

  it('renders the prompt text', () => {
    render(<SceneChallengeOverlay {...defaultProps} />);
    expect(screen.getByText(/A heavy door slams shut/)).toBeInTheDocument();
  });

  it('renders the difficulty number', () => {
    render(<SceneChallengeOverlay {...defaultProps} difficulty={7} />);
    expect(screen.getByLabelText('Difficulty 7')).toBeInTheDocument();
  });

  it('renders breakdown when provided', () => {
    render(
      <SceneChallengeOverlay
        {...defaultProps}
        difficultyBreakdown="Trophy (5) + 2 = 7"
      />
    );
    expect(screen.getByText('Trophy (5) + 2 = 7')).toBeInTheDocument();
  });

  it('shows "The Killer is Here" heading for face cards', () => {
    render(<SceneChallengeOverlay {...defaultProps} isFaceCard />);
    expect(screen.getByText('The Killer is Here')).toBeInTheDocument();
  });

  it('shows "The Finale" heading for jokers', () => {
    render(<SceneChallengeOverlay {...defaultProps} isJoker />);
    expect(screen.getByText('The Finale')).toBeInTheDocument();
  });

  it('applies jumpScare class to backdrop', () => {
    render(<SceneChallengeOverlay {...defaultProps} jumpScare />);
    const dialog = screen.getByRole('dialog');
    // The jump scare class name is generated by vanilla-extract, so we
    // check the element has more than one class (base + jump scare classes)
    expect(dialog.className.split(' ').length).toBeGreaterThan(1);
  });
});
